[theme]
primaryColor = "#1E88E5"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[server]
headless = true
port = 8501
address = "0.0.0.0"  # 允许外部访问

[browser]
gatherUsageStats = false

[runner]
magicEnabled = true

